"""Added winning_outcome_id to market

Revision ID: f6ae8248a6f9
Revises: a2cd29f6fb23
Create Date: 2026-03-10 21:30:27.319854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ae8248a6f9'
down_revision: Union[str, Sequence[str], None] = 'a2cd29f6fb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('winning_outcome_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_market_winning_outcome', 'markets', 'market_outcomes', ['winning_outcome_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_market_winning_outcome', 'markets', type_='foreignkey')
    op.drop_column('markets', 'winning_outcome_id')
    # ### end Alembic commands ###
